# backend/app/services/agents/postprocessing_agent.py

from langchain_core.messages import AIMessage

def postprocess_answer(messages: list):
    print("[Agent] Post-processing answer...")

    answer = messages[-1].content.strip()
    final_output = answer + "\n\n[Generated by Hybrid RAG System]"

    return [AIMessage(content=final_output)]